# This is a basic workflow to help you get started with Actions

name: Update-Blog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Run PowerShell script
      - name: Run PowerShell script
        shell: pwsh
        run: .\converter.ps1
      
      # Git Commit and Push
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: secrets.GITHUB_TOKEN 
