# This is a basic workflow to help you get started with Actions

name: Update-Blog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run
      shell: pwsh
      run: |
        .\converter.ps1
        
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: secrets.GITHUB_TOKEN 
