# General Action information
name: Update-Blog

# Action should run each time a new issue has been opened (created).
on:
  issues:
    types: [opened]

jobs:
  update-blog:
    # Run on ubuntu to save minute quota.
    # Windows has factor 10 per minute.
    # Linux just factor 1.
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Run PowerShell script
      - name: Run PowerShell script
        shell: pwsh
        run: .\converter.ps1
      
      # Git Commit and Push
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: secrets.GITHUB_TOKEN 
